//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace GODInventoryWinForm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
         
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\NAFCO\\NFWE\\client")]
        public string NFWEInstallDir {
            get {
                return ((string)(this["NFWEInstallDir"]));
            }
            set {
                this["NFWEInstallDir"] = value;
            }
        }
        //string path = AppDomain.CurrentDomain.BaseDirectory + "app.config";
        
  
        //[global::System.Configuration.DefaultSettingValueAttribute(@path)]
        //private string 仕入先コード;
        //public string _仕入先コード
        //{
        //    get { return 仕入先コード; }
        //    set { 仕入先コード = value; }
        //}

    }
}
